"""An actual custom generator plus CSV and Garden-language output targets."""
import csv
import io
import re
from markovjunior.procedural import Artifact,Document


def lexicon(params,context):
    count=params.get('entries',24)
    if type(count) is not int or not 1<=count<=500:
        raise ValueError('entries must be 1..500')
    rng=context.random
    meanings=('water','tree','sun','moon','path','home','memory','light')
    words=set()
    rows=[]
    attempts=0
    while len(rows)<count:
        attempts+=1
        if attempts>10000:raise ValueError('lexicon budget exceeded')
        token=''.join('klmnprstv'[rng.next(9)]+'aeiou'[rng.next(5)] for _ in range(2))
        if token in words:continue
        words.add(token)
        rows.append({'token':token,'meaning':meanings[rng.next(len(meanings))],'category':'noun'})
    return Document('data',rows,{'language':'procedural lexicon'})


def csv_output(doc,stem):
    rows=doc.value
    if not isinstance(rows,list) or not rows or not all(isinstance(r,dict) for r in rows):
        raise ValueError('CSV needs a nonempty list of records')
    keys=list(rows[0])
    if any(set(r)!=set(keys) or any(not isinstance(v,(str,int,float,bool)) for v in r.values()) for r in rows):
        raise ValueError('CSV records must have the same scalar fields')
    stream=io.StringIO(newline='')
    writer=csv.DictWriter(stream,fieldnames=keys,lineterminator='\n')
    writer.writeheader()
    writer.writerows(rows)
    return (Artifact(stem+'.csv',stream.getvalue(),'text/csv'),)


def garden_output(doc,stem):
    """Validate and export a tiny original DSL generated by the grammar recipe."""
    text=doc.value
    lines=text.strip().splitlines()
    if len(lines)<3 or not re.fullmatch(r'garden "[^"\n]+" \{',lines[0]) or lines[-1]!='}':
        raise ValueError('invalid garden program')
    plant=re.compile(r'  plant (oak|fern|willow|flower) at \((\d+), (\d+)\) size (\d+);')
    for line in lines[1:-1]:
        match=plant.fullmatch(line)
        if not match or not (0<=int(match[2])<=1000 and 0<=int(match[3])<=600 and 1<=int(match[4])<=30):
            raise ValueError('invalid garden plant command')
    return (Artifact(stem+'.garden',text,'text/plain'),)


def register(registry):
    registry.register_generator('lexicon',lexicon)
    registry.register_target('csv',{'data'},csv_output)
    registry.register_target('garden',{'text'},garden_output)
