/* Install Playwright and Chromium to run: node validation/test_studio.cjs
   STUDIO_CPU=1 disables WebGL. STUDIO_URL selects a local or published site. */
const{chromium}=require('playwright');
const assert=require('assert'),fs=require('fs'),path=require('path'),os=require('os');
const cpu=process.env.STUDIO_CPU==='1',url=process.env.STUDIO_URL||'http://127.0.0.1:8765/';
const artifacts=process.env.STUDIO_ARTIFACT_DIR||path.join(os.tmpdir(),'markov-studio-tests');fs.mkdirSync(artifacts,{recursive:true});
const checks=[],errors=[];
(async()=>{const executablePath=process.env.STUDIO_CHROMIUM||(fs.existsSync('/usr/bin/chromium')?'/usr/bin/chromium':chromium.executablePath());const browser=await chromium.launch({executablePath,headless:true,args:['--no-sandbox',...(cpu?['--disable-webgl']:['--use-angle=swiftshader','--enable-unsafe-swiftshader'])]});
try{
 const page=await browser.newPage({viewport:{width:1600,height:1000},ignoreHTTPSErrors:true,acceptDownloads:true});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.waitForFunction(()=>typeof lastResult!=='undefined'&&lastResult?.ok,{},{timeout:120000});
 assert.equal(await page.evaluate(()=>lastResult.scene.objects.length),40);assert.equal(await page.evaluate(()=>viewport.backend),cpu?'Canvas 2D / CPU':'Babylon.js / WebGL');checks.push('real Python multifile startup and '+(cpu?'CPU rendering without WebGL':'Babylon WebGL rendering'));
 await page.screenshot({path:path.join(artifacts,cpu?'studio_1_0_cpu.png':'studio_1_0_webgl.png'),fullPage:true});
 async function code(source){await page.locator('.cm-content').click();await page.keyboard.press('Control+KeyA');await page.keyboard.insertText(source);}
 async function run(){const before=await page.evaluate(()=>requestId);await page.locator('#run').click();await page.waitForFunction(id=>requestId>id&&!running&&lastResult!==null,before,{timeout:60000});}
 const custom=`from collections import Counter\nclass Engine:\n    def values(self, count):\n        return [i ** 3 for i in range(count)]\ncount = param("count", 3, min=1, max=12, step=1)\nvalues = Engine().values(count)\nfor i, value in enumerate(values):\n    sphere(radius=0.4, position=[i-1, 1, 0], name=f"Item {i}")\nprint("USER_PROGRAM", values)\nemit("custom.json", {"values":values})`;
 await code(custom);await run();assert.equal(await page.evaluate(()=>lastResult.scene.objects.length),3);assert((await page.locator('#console').textContent()).includes('USER_PROGRAM [0, 1, 8]'));checks.push('user-written classes, comprehensions, data, stdout and geometry');
 await page.locator('[aria-label="count"]').evaluate(el=>{el.value='5';el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));});await page.waitForFunction(()=>!running&&lastResult?.scene.objects.length===5,{},{timeout:60000});checks.push('code-declared parameter control reruns the program');
 await code('def broken(:\n    pass');await run();assert.equal(await page.evaluate(()=>lastResult.error.type),'SyntaxError');assert.equal(await page.evaluate(()=>lastResult.error.line),1);assert(await page.locator('.cm-lintRange-error').count()>0);checks.push('syntax error with source line and editor diagnostic');
 await code('print("before error")\n1 / 0');await run();assert.equal(await page.evaluate(()=>lastResult.error.line),2);assert((await page.locator('#console').textContent()).includes('before error'));checks.push('runtime error with line and partial stdout');
 await page.locator('#new-file').click();await page.locator('#file-name').fill('utilities.mp');await page.locator('#create-file').click();await code('def value():\n    return 31');await page.locator('#file-tree button').filter({hasText:'main.mp'}).click();
 await code('from utilities import value\nprint("MODULE",value())\nsphere(position=[0,1,0],name="Editable")\ngenerate("program", {"functions":2}, targets=["python","javascript","typescript","c","cpp","rust","go","lua","sql"])');await run();assert((await page.locator('#console').textContent()).includes('MODULE 31'));assert.equal(await page.evaluate(()=>outputs.length),9);checks.push('editable project modules and all nine IR backend outputs');
 await page.locator('[data-output="files"]').click();await page.locator('#output-file').selectOption('generated.rs');assert((await page.locator('#output-source').textContent()).includes('pub fn proc_000'));await page.locator('[data-output="viewport"]').click();
 await code('node=sphere(position=[0,1,0],name="Animated")\ndef update(t,dt):\n    node.position[0] += dt');await run();await page.locator('#animation').click();await page.waitForFunction(()=>lastResult.scene.objects[0].position[0]>.08,{},{timeout:15000});await page.locator('#animation').click();assert.equal(await page.evaluate(()=>animated),false);checks.push('persistent callback animation and pause');
 await code('while True:\n    pass');await page.locator('#run').click();await page.locator('#stop').click();assert.equal(await page.evaluate(()=>project.files.find(f=>f.name==='main.mp').content),'while True:\n    pass');await page.waitForFunction(()=>workerReady&&!running,{},{timeout:120000});await code('print("RECOVERED")\nsphere(position=[0,1,0],name="Editable")');await run();assert((await page.locator('#console').textContent()).includes('RECOVERED'));checks.push('terminate a running worker, preserve source and execute again');
 await page.evaluate(()=>viewport.select(lastResult.scene.objects[0].id));await page.locator('[aria-label="Posição X"]').fill('3.5');await page.locator('[aria-label="Posição X"]').press('Tab');assert.equal(await page.evaluate(()=>viewport.export().objects[0].position[0]),3.5);checks.push('inspector writes scene transforms');
 const projectDownload=page.waitForEvent('download');await page.locator('#save-project').click();const download=await projectDownload;const downloaded=path.join(artifacts,cpu?'project_cpu.json':'project_webgl.json');await download.saveAs(downloaded);const saved=JSON.parse(fs.readFileSync(downloaded));assert.equal(saved.schema,'markov.project/1');assert.equal(saved.savedScene.objects[0].position[0],3.5);
 await page.locator('#new-project').click();await page.locator('#project-input').setInputFiles(downloaded);await page.waitForFunction(()=>project?.files.some(f=>f.content.includes('RECOVERED')));assert.equal(await page.evaluate(()=>viewport.export().objects[0].position[0]),3.5);checks.push('project JSON saves/reopens code, parameters and edited scene');
 await page.reload();await page.waitForFunction(()=>workerReady,{},{timeout:120000});assert.equal(await page.evaluate(()=>editor.getValue().includes('RECOVERED')),true);assert.equal(await page.evaluate(()=>viewport.export().objects[0].position[0]),3.5);checks.push('browser persistence after reload');
 await page.locator('#share-project').click();const link=await page.locator('#share-link').inputValue();assert(link.includes('#project='));await page.locator('[data-close="share-dialog"]').click();checks.push('shareable source project URL');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);await page.screenshot({path:path.join(artifacts,cpu?'studio_mobile_cpu.png':'studio_mobile_webgl.png'),fullPage:true});checks.push('mobile layout without horizontal overflow');
 assert.deepStrictEqual(errors,[]);console.log(JSON.stringify({ok:true,renderer:cpu?'CPU':'WebGL',url,checks},null,2));fs.writeFileSync(path.join(artifacts,cpu?'studio_cpu_report.json':'studio_webgl_report.json'),JSON.stringify({ok:true,url,renderer:cpu?'CPU':'WebGL',checks},null,2));
}finally{await browser.close();}})().catch(error=>{console.error(error);console.error('Completed checks:',checks);process.exit(1);});
